WIREGUARD_IMAGE: "ghcr.io/jodevsa/wireguard-operator/wireguard:sha-e78fd80cd98f1c904134dbbe0eaf2712ef21e091"
OPERATOR_IMAGE: "ghcr.io/jodevsa/wireguard-operator/operator:sha-e78fd80cd98f1c904134dbbe0eaf2712ef21e091"