WIREGUARD_IMAGE: "ghcr.io/jodevsa/wireguard-operator/wireguard:sha-ef1a92d9154674bdec0b15917cad2243c7b831bb"
OPERATOR_IMAGE: "ghcr.io/jodevsa/wireguard-operator/operator:sha-ef1a92d9154674bdec0b15917cad2243c7b831bb"