WIREGUARD_IMAGE: "ghcr.io/jodevsa/wireguard-operator/wireguard:sha-57d3cf6bb2f3a54ab6f511af835a033075c443d7"
OPERATOR_IMAGE: "ghcr.io/jodevsa/wireguard-operator/operator:sha-57d3cf6bb2f3a54ab6f511af835a033075c443d7"