apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
    operators.operatorframework.io/builder: operator-sdk-v1.17.0
    operators.operatorframework.io/project_layout: go.kubebuilder.io/v3
  name: wireguard-operator.v0.0.1
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions: {}
  description: wireguard
  displayName: wireguard-operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: []
    strategy: deployment
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - operator
  - vpn
  - wireguard
  links:
  - name: Wireguard Operator
    url: https://wireguard-operator.domain
  maintainers:
  - email: subhialhasan@protonmail.com
    name: subhi
  maturity: alpha
  provider:
    name: Subhi AL Hasan
    url: https://github.com/jodevsa/wireguard-operator
  version: 0.0.1
