
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - vpn.example.com
  resources:
  - wireguards
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - vpn.example.com
  resources:
  - wireguards/finalizers
  verbs:
  - update
- apiGroups:
  - vpn.example.com
  resources:
  - wireguards/status
  verbs:
  - get
  - patch
  - update
