# permissions for end users to edit wireguards.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: wireguard-editor-role
rules:
- apiGroups:
  - vpn.example.com
  resources:
  - wireguards
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - vpn.example.com
  resources:
  - wireguards/status
  verbs:
  - get
